        // set variable to be reused to initialize app
        var app = angular.module('myApp', []);

        // copy controller
        app.controller('ContentCtrl', function($scope) {
            $scope.header="Address Book List",
            $scope.introText="This is the frontend framework of an address list, more features can be added next iteration. Filter update upon request."
        })

        // a controller for people
        app.controller("PeopleController",function($scope) {  
            $scope.people=[
                {id:"ALFKI", companyName:"Alfreds Futterkiste", contactName: "Maria Anders", contactTitle:"Sales Representative", address:"Obere Str. 57", city:"Berlin", email:"dummy@gmail.com12209", postal:"12209", country:"Germany", phone:"030-0074321", fax:"030-0076545", region:" "},
                {id:"ANATR", companyName:"Ana Trujillo Emparedados y helados", contactName: "Ana Trujillo", contactTitle:"Owner", address:"Avda. de la Constitución 2222", city:"México D.F.", email:"dummy@gmail.com12209", postal:"05021", country:"Mexico", phone:"(5) 555-4729", fax:"(5) 555-3745", region:" "},
                {id:"ANTON", companyName:"Antonio Moreno Taquería", contactName: "Antonio Moreno", contactTitle:"Owner", address:"Mataderos  2312", city:"México D.F.", email:"dummy@gmail.com12209", postal:"05023", country:"Mexico", phone:"(5) 555-3932", fax:" ", region:" "},
                {id:"AROUT", companyName:"Around the Horn", contactName: "Thomas Hardy", contactTitle:"Sales Representative", address:"120 Hanover Sq.", city:"London", email:"dummy@gmail.com12209", postal:"WA1 1DP", country:"UK", phone:"(171) 555-7788", fax:"(171) 555-6750", region:" "},
                {id:"BERGS", companyName:"Berglunds snabbköp", contactName: "Christina Berglund", contactTitle:"Order Administrator", address:"Berguvsvägen  8", city:"Luleå", email:"dummy@gmail.com12209", postal:"S-958 22", country:"Sweden", phone:"0921-12 34 65", fax:"0921-12 34 67", region:" "},
                {id:"BLAUS", companyName:"Blauer See Delikatessen", contactName: "Hanna Moos", contactTitle:"Sales Representative", address:"Forsterstr. 57", city:"Mannheim", email:"dummy@gmail.com12209", postal:"68306", country:"Germany", phone:"0621-08460", fax:"0621-08924", region:" "},
                {id:"BLONP",companyName:"Blondel père et fils",contactName:"Frédérique Citeaux",contactTitle:"Marketing Manager",address:"24, place Kléber",city:"Strasbourg",email:"dummy@gmail.com",postal:"67000",country:"France",phone:"88.60.15.31",fax:"88.60.15.32",region:""},
                {id:"BOLID",companyName:"Bólido Comidas preparadas",contactName:"Martín Sommer",contactTitle:"Owner",address:"C/ Araquil, 67",city:"Madrid",email:"dummy@gmail.com",postal:"28023",country:"Spain",phone:"(91) 555 22 82",fax:"(91) 555 91 99",region:""},
                {id:"BONAP",companyName:"Bon app'",contactName:"Laurence Lebihan",contactTitle:"Owner",address:"12, rue des Bouchers",city:"Marseille",email:"dummy@gmail.com",postal:"13008",country:"France",phone:"91.24.45.40",fax:"91.24.45.41",region:""},
                {id:"BOTTM",companyName:"Bottom-Dollar Markets",contactName:"Elizabeth Lincoln",contactTitle:"Accounting Manager",address:"23 Tsawassen Blvd.",city:"Tsawassen",email:"dummy@gmail.com",postal:"T2F 8M4",country:"Canada",phone:"(604) 555-4729",fax:"(604) 555-3745",region:"BC"},
                {id:"BSBEV",companyName:"B's Beverages",contactName:"Victoria Ashworth",contactTitle:"Sales Representative",address:"Fauntleroy Circus",city:"London",email:"dummy@gmail.com",postal:"EC2 5NT",country:"UK",phone:"(171) 555-1212",fax:"",region:""},
                {id:"CACTU",companyName:"Cactus Comidas para llevar",contactName:"Patricio Simpson",contactTitle:"Sales Agent",address:"Cerrito 333",city:"Buenos Aires",email:"dummy@gmail.com",postal:"1010",country:"Argentina",phone:"(1) 135-5555",fax:"(1) 135-4892",region:""},
                {id:"CENTC",companyName:"Centro comercial Moctezuma",contactName:"Francisco Chang",contactTitle:"Marketing Manager",address:"Sierras de Granada 9993",city:"México D.F.",email:"dummy@gmail.com",postal:"05022",country:"Mexico",phone:"(5) 555-3392",fax:"(5) 555-7293",region:""},
                {id:"CHOPS",companyName:"Chop-suey Chinese",contactName:"Yang Wang",contactTitle:"Owner",address:"Hauptstr. 29",city:"Bern",email:"dummy@gmail.com",postal:"3012",country:"Switzerland",phone:"0452-076545",fax:"",region:""},
                {id:"COMMI",companyName:"Comércio Mineiro",contactName:"Pedro Afonso",contactTitle:"Sales Associate",address:"Av. dos Lusíadas, 23",city:"São Paulo",email:"dummy@gmail.com",postal:"05432-043",country:"Brazil",phone:"(11) 555-7647",fax:"",region:"SP"},
                {id:"CONSH",companyName:"Consolidated Holdings",contactName:"Elizabeth Brown",contactTitle:"Sales Representative",address:"Berkeley Gardens 12  Brewery",city:"London",email:"dummy@gmail.com",postal:"WX1 6LT",country:"UK",phone:"(171) 555-2282",fax:"(171) 555-9199",region:""},
                {id:"DRACD",companyName:"Drachenblut Delikatessen",contactName:"Sven Ottlieb",contactTitle:"Order Administrator",address:"Walserweg 21",city:"Aachen",email:"dummy@gmail.com",postal:"52066",country:"Germany",phone:"0241-039123",fax:"0241-059428",region:""},
                {id:"DUMON",companyName:"Du monde entier",contactName:"Janine Labrune",contactTitle:"Owner",address:"67, rue des Cinquante Otages",city:"Nantes",email:"dummy@gmail.com",postal:"44000",country:"France",phone:"40.67.88.88",fax:"40.67.89.89",region:""},
                {id:"EASTC",companyName:"Eastern Connection",contactName:"Ann Devon",contactTitle:"Sales Agent",address:"35 King George",city:"London",email:"dummy@gmail.com",postal:"WX3 6FW",country:"UK",phone:"(171) 555-0297",fax:"(171) 555-3373",region:""},
                {id:"ERNSH",companyName:"Ernst Handel",contactName:"Roland Mendel",contactTitle:"Sales Manager",address:"Kirchgasse 6",city:"Graz",email:"dummy@gmail.com",postal:"8010",country:"Austria",phone:"7675-3425",fax:"7675-3426",region:""},
                {id:"FAMIA",companyName:"Familia Arquibaldo",contactName:"Aria Cruz",contactTitle:"Marketing Assistant",address:"Rua Orós, 92",city:"São Paulo",email:"dummy@gmail.com",postal:"05442-030",country:"Brazil",phone:"(11) 555-9857",fax:"",region:"SP"},
                {id:"FISSA",companyName:"FISSA Fabrica Inter. Salchichas S.A.",contactName:"Diego Roel",contactTitle:"Accounting Manager",address:"C/ Moralzarzal, 86",city:"Madrid",email:"dummy@gmail.com",postal:"28034",country:"Spain",phone:"(91) 555 94 44",fax:"(91) 555 55 93",region:""},
                {id:"FOLIG",companyName:"Folies gourmandes",contactName:"Martine Rancé",contactTitle:"Assistant Sales Agent",address:"184, chaussée de Tournai",city:"Lille",email:"dummy@gmail.com",postal:"59000",country:"France",phone:"20.16.10.16",fax:"20.16.10.17",region:""},
                {id:"FOLKO",companyName:"Folk och fä HB",contactName:"Maria Larsson",contactTitle:"Owner",address:"Åkergatan 24",city:"Bräcke",email:"dummy@gmail.com",postal:"S-844 67",country:"Sweden",phone:"0695-34 67 21",fax:"",region:""},
                {id:"FRANK",companyName:"Frankenversand",contactName:"Peter Franken",contactTitle:"Marketing Manager",address:"Berliner Platz 43",city:"München",email:"dummy@gmail.com",postal:"80805",country:"Germany",phone:"089-0877310",fax:"089-0877451",region:""},
                {id:"FRANR",companyName:"France restauration",contactName:"Carine Schmitt",contactTitle:"Marketing Manager",address:"54, rue Royale",city:"Nantes",email:"dummy@gmail.com",postal:"44000",country:"France",phone:"40.32.21.21",fax:"40.32.21.20",region:""},
                {id:"FRANS",companyName:"Franchi S.p.A.",contactName:"Paolo Accorti",contactTitle:"Sales Representative",address:"Via Monte Bianco 34",city:"Torino",email:"dummy@gmail.com",postal:"10100",country:"Italy",phone:"011-4988260",fax:"011-4988261",region:""},
                {id:"FURIB",companyName:"Furia Bacalhau e Frutos do Mar",contactName:"Lino Rodriguez",contactTitle:"Sales Manager",address:"Jardim das rosas n. 32",city:"Lisboa",email:"dummy@gmail.com",postal:"1675",country:"Portugal",phone:"(1) 354-2534",fax:"(1) 354-2535",region:""},
                {id:"GALED",companyName:"Galería del gastrónomo",contactName:"Eduardo Saavedra",contactTitle:"Marketing Manager",address:"Rambla de Cataluña, 23",city:"Barcelona",email:"dummy@gmail.com",postal:"08022",country:"Spain",phone:"(93) 203 4560",fax:"(93) 203 4561",region:""},
                {id:"GODOS",companyName:"Godos Cocina Típica",contactName:"José Pedro Freyre",contactTitle:"Sales Manager",address:"C/ Romero, 33",city:"Sevilla",email:"dummy@gmail.com",postal:"41101",country:"Spain",phone:"(95) 555 82 82",fax:"",region:""},
                {id:"GOURL",companyName:"Gourmet Lanchonetes",contactName:"André Fonseca",contactTitle:"Sales Associate",address:"Av. Brasil, 442",city:"Campinas",email:"dummy@gmail.com",postal:"04876-786",country:"Brazil",phone:"(11) 555-9482",fax:"",region:"SP"},
                {id:"GREAL",companyName:"Great Lakes Food Market",contactName:"Howard Snyder",contactTitle:"Marketing Manager",address:"2732 Baker Blvd.",city:"Eugene",email:"dummy@gmail.com",postal:"97403",country:"USA",phone:"(503) 555-7555",fax:"",region:"OR"},
                {id:"GROSR",companyName:"GROSELLA-Restaurante",contactName:"Manuel Pereira",contactTitle:"Owner",address:"5ª Ave. Los Palos Grandes",city:"Caracas",email:"dummy@gmail.com",postal:"1081",country:"Venezuela",phone:"(2) 283-2951",fax:"(2) 283-3397",region:"DF"},
                {id:"HANAR",companyName:"Hanari Carnes",contactName:"Mario Pontes",contactTitle:"Accounting Manager",address:"Rua do Paço, 67",city:"Rio de Janeiro",email:"dummy@gmail.com",postal:"05454-876",country:"Brazil",phone:"(21) 555-0091",fax:"(21) 555-8765",region:"RJ"},
                {id:"HILAA",companyName:"HILARIÓN-Abastos",contactName:"Carlos Hernández",contactTitle:"Sales Representative",address:"Carrera 22 con Ave. Carlos Soublette #8-35",city:"San Cristóbal",email:"dummy@gmail.com",postal:"5022",country:"Venezuela",phone:"(5) 555-1340",fax:"(5) 555-1948",region:"Táchira"},
                {id:"HUNGC",companyName:"Hungry Coyote Import Store",contactName:"Yoshi Latimer",contactTitle:"Sales Representative",address:"City Center Plaza 516 Main St.",city:"Elgin",email:"dummy@gmail.com",postal:"97827",country:"USA",phone:"(503) 555-6874",fax:"(503) 555-2376",region:"OR"},
                {id:"HUNGO",companyName:"Hungry Owl All-Night Grocers",contactName:"Patricia McKenna",contactTitle:"Sales Associate",address:"8 Johnstown Road",city:"Cork",email:"dummy@gmail.com",postal:"",country:"Ireland",phone:"2967 542",fax:"2967 3333",region:"Co. Cork"},
                {id:"ISLAT",companyName:"Island Trading",contactName:"Helen Bennett",contactTitle:"Marketing Manager",address:"Garden House Crowther Way",city:"Cowes",email:"dummy@gmail.com",postal:"PO31 7PJ",country:"UK",phone:"(198) 555-8888",fax:"",region:"Isle of Wight"},
                {id:"KOENE",companyName:"Königlich Essen",contactName:"Philip Cramer",contactTitle:"Sales Associate",address:"Maubelstr. 90",city:"Brandenburg",email:"dummy@gmail.com",postal:"14776",country:"Germany",phone:"0555-09876",fax:"",region:""},
                {id:"LACOR",companyName:"La corne d'abondance",contactName:"Daniel Tonini",contactTitle:"Sales Representative",address:"67, avenue de l'Europe",city:"Versailles",email:"dummy@gmail.com",postal:"78000",country:"France",phone:"30.59.84.10",fax:"30.59.85.11",region:""},
                {id:"LAMAI",companyName:"La maison d'Asie",contactName:"Annette Roulet",contactTitle:"Sales Manager",address:"1 rue Alsace-Lorraine",city:"Toulouse",email:"dummy@gmail.com",postal:"31000",country:"France",phone:"61.77.61.10",fax:"61.77.61.11",region:""},
                {id:"LAUGB",companyName:"Laughing Bacchus Wine Cellars",contactName:"Yoshi Tannamuri",contactTitle:"Marketing Assistant",address:"1900 Oak St.",city:"Vancouver",email:"dummy@gmail.com",postal:"V3F 2K1",country:"Canada",phone:"(604) 555-3392",fax:"(604) 555-7293",region:"BC"},
                {id:"LAZYK",companyName:"Lazy K Kountry Store",contactName:"John Steel",contactTitle:"Marketing Manager",address:"12 Orchestra Terrace",city:"Walla Walla",email:"dummy@gmail.com",postal:"99362",country:"USA",phone:"(509) 555-7969",fax:"(509) 555-6221",region:"WA"},
                {id:"LEHMS",companyName:"Lehmanns Marktstand",contactName:"Renate Messner",contactTitle:"Sales Representative",address:"Magazinweg 7",city:"Frankfurt a.M.",email:"dummy@gmail.com",postal:"60528",country:"Germany",phone:"069-0245984",fax:"069-0245874",region:""},
                {id:"LETSS",companyName:"Let's Stop N Shop",contactName:"Jaime Yorres",contactTitle:"Owner",address:"87 Polk St. Suite 5",city:"San Francisco",email:"dummy@gmail.com",postal:"94117",country:"USA",phone:"(415) 555-5938",fax:"",region:"CA"},
                {id:"LILAS",companyName:"LILA-Supermercado",contactName:"Carlos González",contactTitle:"Accounting Manager",address:"Carrera 52 con Ave. Bolívar #65-98 Llano Largo",city:"Barquisimeto",email:"dummy@gmail.com",postal:"3508",country:"Venezuela",phone:"(9) 331-6954",fax:"(9) 331-7256",region:"Lara"},
                {id:"LINOD",companyName:"LINO-Delicateses",contactName:"Felipe Izquierdo",contactTitle:"Owner",address:"Ave. 5 de Mayo Porlamar",city:"I. de Margarita",email:"dummy@gmail.com",postal:"4980",country:"Venezuela",phone:"(8) 34-56-12",fax:"(8) 34-93-93",region:"Nueva Esparta"},
                {id:"LONEP",companyName:"Lonesome Pine Restaurant",contactName:"Fran Wilson",contactTitle:"Sales Manager",address:"89 Chiaroscuro Rd.",city:"Portland",email:"dummy@gmail.com",postal:"97219",country:"USA",phone:"(503) 555-9573",fax:"(503) 555-9646",region:"OR"},
                {id:"MAGAA",companyName:"Magazzini Alimentari Riuniti",contactName:"Giovanni Rovelli",contactTitle:"Marketing Manager",address:"Via Ludovico il Moro 22",city:"Bergamo",email:"dummy@gmail.com",postal:"24100",country:"Italy",phone:"035-640230",fax:"035-640231",region:""},
                {id:"MAISD",companyName:"Maison Dewey",contactName:"Catherine Dewey",contactTitle:"Sales Agent",address:"Rue Joseph-Bens 532",city:"Bruxelles",email:"dummy@gmail.com",postal:"B-1180",country:"Belgium",phone:"(02) 201 24 67",fax:"(02) 201 24 68",region:""}
            ];
        } )